name: Helm

on:
  push:
    branches:
    - master
    - publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Release
      uses: helm/chart-releaser-action@v1.0.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
